import type { Metadata } from "next";
import { Delius } from "next/font/google"; // Updated font import
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Loading from "./loading";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import ScrollToTop from "./_components/scroll-to-top";
import { WarningDialog } from "./_components/WarningDialog";

const delius = Delius({
  variable: "--font-delius",
  subsets: ["latin"],
  weight: ["400"], // Delius only has 400 weight
});



export const metadata: Metadata = {
  title: "StoryCareer",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon-black.svg", media: "(prefers-color-scheme: light)" },
    { rel: "icon", url: "/favicon-white.svg", media: "(prefers-color-scheme: dark)" },
  ],
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${delius.className}  antialiased`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            
          >
            <ClerkLoading>
              <Loading />
            </ClerkLoading>
            <ClerkLoaded>
              <WarningDialog />
              {children}
              <ScrollToTop />
              <Toaster />
            </ClerkLoaded>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
